version: "3.9"
services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/users_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 1

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/orders_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 1

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
