ktor:
  application:
    modules:
      - com.example.user_service.UserServiceApplicationKt.module
  deployment:
    port: 8080

database:
  host: "$POSTGRES_HOST:postgres"
  port: "$POSTGRES_PORT:5432"
  user: "$POSTGRES_USER:postgres"
  password: "$POSTGRES_PASSWORD:1"
  name: "$POSTGRES_DB:ma_database"

