ktor:
  application:
    modules:
      - com.example.user_service.UserServiceApplicationKt.module
  deployment:
    port: 8080

database:
  url: "jdbc:postgresql://localhost:5432/ma_database"
  driver: org.postgresql.Driver
  user: postgres
  password: 1
