ktor:
  application:
    modules:
      - com.example.order_service.OrderServiceApplicationKt.module
  deployment:
    port: 9090

database:
  host: "$POSTGRES_HOST:postgres"
  port: "$POSTGRES_PORT:5432"
  user: "$POSTGRES_USER:postgres"
  password: "$POSTGRES_PASSWORD:1"
  name: "$POSTGRES_DB:ma_database"

